name=Ethernet
version=0.1.0
author=Cal ABEL
maintainer=Cal ABEL
sentence=Ethernet support for SAMD/SAME devices.
paragraph=Provides an Arduino-facing Ethernet API layered over the GMAC core hardware module and PHY utilities.
category=Communication
url=https://github.com/adafruit/ArduinoCore-samd
architectures=samd
