/*
  Copyright (c) 2014-2015 Arduino LLC.  All right reserved.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "variant.h"

/*
 * Pins descriptions
 */

const PinDescription g_APinDescription[] =
    {
        // 0..15: EXT1. UART first, then GPIO/PWM/IRQ/SPI/ADC/I2C.
        {PORTA, 5, PIO_SERCOM, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel5, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5},
        {PORTA, 4, PIO_SERCOM, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel4, NOT_ON_PWM, TC0_CH0, EXTERNAL_INT_4},
        {PORTA, 6, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG | PIN_ATTR_PWM_E, ADC_Channel6, TC1_CH0, TC1_CH0, EXTERNAL_INT_6},
        {PORTA, 7, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG | PIN_ATTR_PWM_E, ADC_Channel7, TC1_CH1, TC1_CH1, EXTERNAL_INT_7},
        {PORTB, 8, PIO_TIMER, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG | PIN_ATTR_PWM_E, ADC_Channel2, TC4_CH0, TC4_CH0, EXTERNAL_INT_8},
        {PORTB, 9, PIO_TIMER, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG | PIN_ATTR_PWM_E, ADC_Channel3, TC4_CH1, TC4_CH1, EXTERNAL_INT_9},
        {PORTB, 7, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel9, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7},
        {PORTA, 27, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_11},
        {PORTB, 28, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_14},
        {PORTB, 27, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_13},
        {PORTB, 29, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_15},
        {PORTB, 26, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_12},
        {PORTB, 4, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel6, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4},
        {PORTB, 5, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel7, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5},
        {PORTA, 22, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, TC4_CH0, EXTERNAL_INT_6},
        {PORTA, 23, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, TC4_CH1, EXTERNAL_INT_7},

        // 16..31: EXT2, including the I2C/SPI lines shared with EXT3.
        {PORTB, 17, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, TC6_CH1, EXTERNAL_INT_1},
        {PORTB, 16, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, TC6_CH0, EXTERNAL_INT_0},
        {PORTB, 1, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel13, NOT_ON_PWM, TC7_CH1, EXTERNAL_INT_1},
        {PORTB, 6, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel8, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6},
        {PORTB, 14, PIO_TIMER_ALT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC4_CH0, TC5_CH0, EXTERNAL_INT_14},
        {PORTB, 15, PIO_TIMER_ALT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC4_CH1, TC5_CH1, EXTERNAL_INT_15},
        {PORTD, 0, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel14, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0},
        {PORTB, 2, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG | PIN_ATTR_PWM_E, ADC_Channel14, TC6_CH0, TC6_CH0, EXTERNAL_INT_2},
        {PORTC, 6, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6},
        {PORTC, 4, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4},
        {PORTC, 7, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9},
        {PORTC, 5, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5},
        {PORTB, 0, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel12, NOT_ON_PWM, TC7_CH0, EXTERNAL_INT_0},
        {PORTA, 3, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel1, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3},
        {PORTD, 8, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3},
        {PORTD, 9, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4},

        // 32..42: EXT3 pins that are not duplicates of EXT2 shared buses.
        {PORTC, 23, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7},
        {PORTC, 22, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6},
        {PORTC, 1, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel11, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_1},
        {PORTC, 10, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC0_CH0, NOT_ON_TIMER, EXTERNAL_INT_10},
        {PORTD, 10, PIO_TIMER_ALT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC0_CH3, NOT_ON_TIMER, EXTERNAL_INT_5},
        {PORTD, 11, PIO_TIMER_ALT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC0_CH4, NOT_ON_TIMER, EXTERNAL_INT_6},
        {PORTC, 30, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel12, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_14},
        {PORTC, 31, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel13, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_15},
        {PORTC, 14, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_14},
        {PORTC, 2, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel4, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2},
        {PORTC, 3, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG_ALT, ADC_Channel5, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3},

        // 43..46: dedicated ADC/DAC header and PDEC header.
        {PORTA, 2, PIO_ANALOG, PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG, ADC_Channel0, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2},
        {PORTC, 16, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0},
        {PORTC, 17, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_1},
        {PORTC, 18, PIO_DIGITAL, PIN_ATTR_DIGITAL | PIN_ATTR_PWM_F, No_ADC_Channel, TCC0_CH2, NOT_ON_TIMER, EXTERNAL_INT_2},

        // 47..58: internal EDBG UART, target USB, and onboard QSPI flash.
        {PORTB, 24, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_8},
        {PORTB, 25, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9},
        {PORTC, 0, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0},
        {PORTC, 19, PIO_COM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3},
        {PORTA, 24, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_8},
        {PORTA, 25, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9},
        {PORTB, 10, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_10},
        {PORTB, 11, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_11},
        {PORTA, 8, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NMI},
        {PORTA, 9, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9},
        {PORTA, 10, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_10},
        {PORTA, 11, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_11},
        {PORTB, 31, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_15},
};

static_assert(sizeof(g_APinDescription) / sizeof(g_APinDescription[0]) == PINS_COUNT,
              "xplained_m4 pin count does not match g_APinDescription");

const uint8_t g_AAnalogPinMap[NUM_ANALOG_INPUTS] = {
    PIN_A0, PIN_A1, PIN_A2, PIN_A3, PIN_A4, PIN_A5, PIN_A6, PIN_A7,
    PIN_A8, PIN_A9, PIN_A10, PIN_A11, PIN_A12, PIN_A13, PIN_A14, PIN_A15,
};

const void *g_apTCInstances[ARDUINO_TCC_INSTANCE_COUNT + ARDUINO_TC_INSTANCE_COUNT] = {
    TCC0_REGS, TCC1_REGS, TCC2_REGS, TCC3_REGS, TCC4_REGS,
    TC0_REGS, TC1_REGS, TC2_REGS, TC3_REGS, TC4_REGS, TC5_REGS,
    TC6_REGS, TC7_REGS};
const uint32_t GCLK_CLKCTRL_IDs[ARDUINO_TCC_INSTANCE_COUNT + ARDUINO_TC_INSTANCE_COUNT] = {
    TCC0_GCLK_ID, TCC1_GCLK_ID, TCC2_GCLK_ID, TCC3_GCLK_ID, TCC4_GCLK_ID,
    TC0_GCLK_ID, TC1_GCLK_ID, TC2_GCLK_ID, TC3_GCLK_ID, TC4_GCLK_ID,
    TC5_GCLK_ID, TC6_GCLK_ID, TC7_GCLK_ID};

// Multi-serial objects instantiation
SERCOM sercom0(SERCOM0_REGS);
SERCOM sercom1(SERCOM1_REGS);
SERCOM sercom2(SERCOM2_REGS);
SERCOM sercom3(SERCOM3_REGS);
SERCOM sercom4(SERCOM4_REGS);
SERCOM sercom5(SERCOM5_REGS);
SERCOM sercom6(SERCOM6_REGS);
SERCOM sercom7(SERCOM7_REGS);

Uart Serial1(&PERIPH_SERIAL1, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX);
Uart Serial2(&PERIPH_SERIAL2, PIN_SERIAL2_RX, PIN_SERIAL2_TX, PAD_SERIAL2_RX, PAD_SERIAL2_TX);
Uart Serial3(&PERIPH_SERIAL3, PIN_SERIAL3_RX, PIN_SERIAL3_TX, PAD_SERIAL3_RX, PAD_SERIAL3_TX);
Uart Serial4(&PERIPH_SERIAL4, PIN_SERIAL4_RX, PIN_SERIAL4_TX, PAD_SERIAL4_RX, PAD_SERIAL4_TX);

#define UART_HANDLERS(prefix, serial)                                \
    void prefix##_IT_HANDLER_0(void) { serial.IrqHandler(); }         \
    void prefix##_IT_HANDLER_1(void) { serial.IrqHandler(); }         \
    void prefix##_IT_HANDLER_2(void) { serial.IrqHandler(); }         \
    void prefix##_IT_HANDLER_OTHER(void) { serial.IrqHandler(); }

UART_HANDLERS(SERIAL1, Serial1)
UART_HANDLERS(SERIAL2, Serial2)
UART_HANDLERS(SERIAL3, Serial3)
UART_HANDLERS(SERIAL4, Serial4)
